### ISSUE TITLE
Analysis system chokes in sea ice timeseries for 2000 date data

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#81] opened 2017-01-23 23:00 UTC
The analysis system cannot handle the following setting:
[time]
climo_yr1 = 1960
climo_yr2 = 1961
yr_offset = 0
timeseries_yr1 = 1960
timeseries_yr2 = 1961

I get the following error:
[akt@wf-fe1 MPAS-Analysis]$ python run_analysis.py -f config.analysis

Plotting sea-ice area and volume time series...
Reading files /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1959-12.nc through /net/scratch2/akt/MPAS/rundirs/rundir_QU60km_polar/analysis_members/timeSeriesStatsMonthly.1962-01.nc
  Load sea-ice data...
  Compute NH and SH time series of iceAreaCell...
  Make plots...
Traceback (most recent call last):
  File "run_analysis.py", line 182, in <module>
    analysis(config)
  File "run_analysis.py", line 154, in analysis
    variableMap=seaIceVariableMap)
  File "/turquoise/usr/projects/climate/akt/MPAS/analysis/MPAS-Analysis/mpas_analysis/sea_ice/timeseries.py", line 219, in seaice_timeseries
    preprocess=lambda x: preprocess_mpas(x,
  File "/usr/projects/climate/SHARED_CLIMATE/anaconda_envs/default-2.7/lib/python2.7/site-packages/xarray/backends/api.py", line 306, in open_mfdataset
    datasets = [preprocess(ds) for ds in datasets]
  File "/turquoise/usr/projects/climate/akt/MPAS/analysis/MPAS-Analysis/mpas_analysis/sea_ice/timeseries.py", line 220, in <lambda>
    yearoffset=yr_offset))
  File "/turquoise/usr/projects/climate/akt/MPAS/analysis/MPAS-Analysis/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 317, in preprocess_mpas
    assert_valid_datetimes(datetimes, yearoffset)
  File "/turquoise/usr/projects/climate/akt/MPAS/analysis/MPAS-Analysis/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 88, in assert_valid_datetimes
    ' must be large enough to ensure datetimes larger than year 1678'
AssertionError: ERROR: yearoffset=0 must be large enough to ensure datetimes larger than year 1678

**Comment by xylar** [comment] 2017-01-24 07:30
Hi @akturner, could you tell us a little more about the data set you're trying to analyze? Typical ACME runs start at year 0001, but this year is thought of as being 1850 or 2000, so we set yr_offset to either 1849 or 1999.

If your run is similar (i.e. it didn't start in something like 1960 but rather at 0001), I think you would want something similar where you have yr_offset = 1959 and your analysis is then over years 1 to 2.  If this is the case, we need better documentation within our example config file (which itself needs to be generalized as you pointed out in #80).

If, instead, your simulation did, in fact, start at year 1960 and those are the dates used internally in MPAS-SI output files, it sounds like you found a bug we need to look into.  We haven't had data of this type so far so it wouldn't be surprising if we have some issues to iron out.

Either way, maybe you can share with us the full config file you were using?

For some background, `yr_offset` is an unfortunate requirement to work with the format used for dates and times in xarray.  Dates must be in the range of years 1678 to 2262.  This is related to a known deficiency in how times are represented in `pandas`, one of the libraries underlying xarray that we use to load data.  It appears that an alternative way of representing time (`netcdftime.datetime`) is now also supported in xarray and we're working on incorporating it into the analysis right now (see, e.g. #69).

**Comment by xylar** [comment] 2017-01-24 14:02
Thanks @akturner, this is, indeed a bug.

@milenaveneziani, I'm going to hand this off to you because I'm not sure how we want to handle this.  The problem is that we use the same `yr_offset` for the MPAS input data and for the observations or v0 data with which we want to compare.  There's no reason they should be required to be the same.
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/timeseries.py#L103
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/mpas_analysis/sea_ice/timeseries.py#L133

Presumably some cleanup of the config file is needed.  We need a clear section for each of the various types of observations (with a lot of cleanup hopefully taking place when that happens).  One thing that would be part of that reorganization would be to have a yr_offset for each observational data set or group of observations.

**Comment by pwolfram** [comment] 2017-01-24 15:17
@xylar and @milenaveneziani, I'm thinking we need a new approach to this `yr_offset` issue.  What about automatically determining an appropriate year using `yr_offset` as a target, probably renaming to `starting_year`?  If we did that then there should be no problem here because both analysis would start at `yr_offset=> starting_year ~ 1850` or such and there would be no bug.  

However, at this point the date specification, unless we are talking actual climate years (preindustrial to ~2100), is artificial.  Maybe the better approach is to have the code ask the question, "Is this a real year?"  If so, then just use the date, otherwise, shift starting point to `yr_offset` or `starting_year`.  

I'm happy to work on this but want to follow up with you both before doing this because the date issue is causing a lot of problems and if we are clever we may be able to design away > 80% of the issues with some type of simple approach along the lines of adding a little more logic.

**Comment by milenaveneziani** [comment] 2017-01-24 17:56
As a big picture, let us remember that this year_offset thing is only needed for time series.

The only reason that we are using the same year_offset for obs and ACME v0 is that we want to overlap the model time series with the obs and v0 time series.

The solution I had in mind was simple, and similar to what @pwolfram said: check for the first model year, if it's >1678 then set year_offset=0 no matter what value was chosen in the config file (issuing a warning if the config value is different).

**Comment by xylar** [comment] 2017-01-24 21:29
Yes, these approach sound essentially the same and they make sense to me.  I don't have any time to work on this right now but I could review if one of you submits a PR.

**Comment by pwolfram** [comment] 2017-01-26 00:09
Are we in agreement @xylar and @milenaveneziani that we should just employ a simple fix for this in the time-being?  I'm happy to submit a PR if we have consensus.  

Also, @akturner, do you mind sharing your path location and a copy of the `config.analysis` file so that we can reproduce this error to ensure that it is fixed?

**Comment by milenaveneziani** [comment] 2017-01-26 07:01
That sounds good @pwolfram, thanks.

**Comment by xylar** [comment] 2017-01-26 07:36
@pwolfram, yes I think we already had consensus so please go ahead.  Things are moving slowly enough in this repo that I think you can feel free to try solutions without reaching consensus anyway.

@akturner has already given us his config file above:
/turquoise/usr/projects/climate/akt/MPAS/analysis/sea_ice_config/config.ocnice_tutorial
You can figure out all paths from that.  I was able to use it to reproduce he bug.

**Comment by pwolfram** [comment] 2017-01-26 21:21
@xylar, I've submitted a PR to address this issue (#83) with associated config file of /lustre/scratch3/turquoise/pwolfram/MPAS-Analysis/config.analysis_seaice_bug.  We should be able to close this issue following completion of #83.

**Comment by milenaveneziani** [comment] 2017-02-22 23:09
@akturner: this issue was addressed by #111. You may want to retry the analysis with the newer code that does **not** have a year_offset at all.

**Closed by milenaveneziani** 2017-02-22 23:09 UTC
Labels: bug, mpas_xarray
