### ISSUE TITLE
Which version of xarray is the correct one?

### ISSUE THREAD

**Issue by akturner** [MPAS-Dev/MPAS-Analysis#189] opened 2017-04-17 15:00 UTC
Hi, I'm trying to run the sea ice MPAS Tools on my laptop and am encountering the following problem:
pn1512828:MPAS-Analysis akt$ ./run_analysis.py config.setup
/Users/akt/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Plotting sea-ice area and volume time series...

Reading files:
timeSeriesStatsMonthly.1959-12.nc through
timeSeriesStatsMonthly.1962-01.nc
Load sea-ice data...
Warning: Preprocessed time series ends before the timeSeries startYear and will not be plotted.
Caching NH data
Read in previously computed time series
Make NH plots...
Traceback (most recent call last):
File "./run_analysis.py", line 230, in 
analysis(config)
File "./run_analysis.py", line 173, in analysis
seaice_timeseries(config)
File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/sea_ice/timeseries.py", line 231, in seaice_timeseries
obs[key] = replicate_cycle(plotVars[key], dsObs.IceArea, calendar)
File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/sea_ice/timeseries.py", line 396, in replicate_cycle
dsShift = dsToReplicate.copy()
File "/Users/akt/anaconda/lib/python2.7/site-packages/xarray/core/dataarray.py", line 598, in copy
variable = self.variable.copy(deep=deep)
File "/Users/akt/anaconda/lib/python2.7/site-packages/xarray/core/variable.py", line 444, in copy
data = data.copy()
AttributeError: 'Array' object has no attribute 'copy'

This seem like it might be the xarray version thats the problem. I'm using 0.9.2. What is the recommended version?

**Comment by pwolfram** [comment] 2017-04-17 15:08
This is an error from the 0.8 to 0.9 xarray upgrade that was not caught following a refractor of `replicate_cycle`. 0.9.2 is the recommended version although following some bug fixes I'd really say 0.9.3 is the recommended version of xarray.

Note, this is a legitimate bug as far as I can tell-- cc @xylar

**Comment by akturner** [comment] 2017-04-17 15:10
conda upgrade xarray leave me still at 0.9.2

**Comment by pwolfram** [comment] 2017-04-17 15:11
@akturner, can you please try the conda-forge channel if you want to upgrade?

**Comment by pwolfram** [comment] 2017-04-17 15:12
@milenaveneziani and @xylar, did this bug come up during the 0.2 testing process?  If not, is it possible this is a conda environment issue?  It seems unlikely but if so this is the easiest fix.

@akturner, can you please provide more details so that this bug can be reproduced (e.g.: machine, config file, etc)?

**Comment by akturner** [comment] 2017-04-17 15:16
OSX MacBook Pro, conda 4.3.16
[config.setup.txt](https://github.com/MPAS-Dev/MPAS-Analysis/files/925885/config.setup.txt)

**Comment by akturner** [comment] 2017-04-17 15:34
@pwolfram: Conda forge channel?

**Comment by xylar** [comment] 2017-04-17 16:11
@akturner, did you install using the instructions in the readme file?
```
conda config --add channels conda-forge
conda install numpy scipy matplotlib netCDF4 xarray dask bottleneck basemap lxml nco
```
I don't think this is a straightforward problem with the xarray version, as we haven't seen this on any other platforms.  But it also sounds like you're using the same version of xarray as we are (0.9.2).  @pwolfram, I don't think 0.9.3 is available yet, or if so only recently.  Either way, I don't think it relates to this problem.

I don't have OSX so I can't check this myself.  I don't think the conda version matters.

**Comment by xylar** [comment] 2017-04-17 16:12
@akturner, can you send the output of `conda list -e`?

**Comment by akturner** [comment] 2017-04-17 16:52
pn1512828:MPAS-Analysis akt$ conda list -e
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
_license=1.1=py27_1
abstract-rendering=0.5.1=np110py27_0
alabaster=0.7.6=py27_0
anaconda=custom=py27_0
anaconda-client=1.2.1=py27_0
appnope=0.1.0=py27_0
appscript=1.0.1=py27_0
argcomplete=1.0.0=py27_1
astropy=1.0.6=np110py27_0
babel=2.1.1=py27_0
backports_abc=0.4=py27_0
basemap=1.0.8.dev0=np110py27_2
beautifulsoup4=4.4.1=py27_0
bitarray=0.8.1=py27_0
blaze-core=0.8.3=py27_0
bokeh=0.10.0=py27_0
boto=2.38.0=py27_0
bottleneck=1.0.0=np110py27_0
bzip2=1.0.6=1
cartopy=0.13.0=np110py27_2
cdecimal=2.3=py27_0
cffi=1.9.1=py27_0
chest=0.2.3=py27_0
cloudpickle=0.1.1=py27_0
clyent=1.2.0=py27_0
colorama=0.3.3=py27_0
conda=4.3.16=py27_0
conda-build=1.18.2=py27_0
conda-env=2.6.0=0
configobj=5.0.6=py27_0
cryptography=1.7.1=py27_0
curl=7.45.0=0
cycler=0.9.0=py27_0
cython=0.23.4=py27_1
cytoolz=0.7.4=py27_0
dask=0.7.6=py27_0
datashape=0.4.7=np110py27_1
decorator=4.0.4=py27_0
dill=0.2.4=py27_0
docutils=0.12=py27_0
dynd-python=0.7.0=py27_0
enum34=1.0.4=py27_0
esmf=7.0.0=6
expat=2.1.0=2
fastcache=1.0.2=py27_0
flask=0.10.1=py27_1
freetype=2.5.5=1
freexl=1.0.2=1
funcsigs=0.4=py27_0
g2clib=1.6.0=2
gdal=2.1.2=np110py27_1
geos=3.4.2=4
gevent=1.0.1=py27_0
gevent-websocket=0.9.3=py27_0
giflib=5.1.4=0
greenlet=0.4.9=py27_0
grin=1.2.1=py27_1
gsl=2.2.1=1
h5py=2.6.0=np110py27_7
hdf4=4.2.12=0
hdf5=1.8.17=9
hdfeos2=2.19.1=7
hdfeos5=5.1.15=6
heapdict=1.0.0=py27_0
icu=54.1=0
idna=2.0=py27_0
ipaddress=1.0.14=py27_0
ipykernel=4.1.1=py27_0
ipython=4.0.1=py27_0
ipython-notebook=4.0.4=py27_0
ipython-qtconsole=4.0.1=py27_0
ipython_genutils=0.1.0=py27_0
ipywidgets=4.1.0=py27_0
itsdangerous=0.24=py27_0
jasper=1.900.1=4
jbig=2.1=0
jdcal=1.0=py27_0
jedi=0.9.0=py27_0
jinja2=2.8=py27_0
jpeg=9b=0
json-c=0.12=0
jsonschema=2.4.0=py27_0
jupyter=1.0.0=py27_1
jupyter_client=4.1.1=py27_0
jupyter_console=4.0.3=py27_0
jupyter_core=4.0.6=py27_0
kealib=1.4.6=3
krb5=1.13.2=0
launcher=1.0.0=3
libdap4=3.18.3=2
libdynd=0.7.0=0
libgcc=4.8.5=1
libgfortran=3.0.0=0
libiconv=1.14=4
libnetcdf=4.4.1.1=4
libpng=1.6.28=0
libpq=9.5.4=3
libspatialite=4.3.0a=11
libtiff=4.0.6=5
libxml2=2.9.2=0
libxslt=1.1.28=2
llvmlite=0.8.0=py27_0
locket=0.2.0=py27_0
lxml=3.4.4=py27_0
markupsafe=0.23=py27_0
matplotlib=1.5.1=np110py27_0
mistune=0.7.1=py27_0
mkl=11.3.1=0
mock=1.3.0=py27_0
mpich=3.2=4
multipledispatch=0.4.8=py27_0
nbconvert=4.0.0=py27_0
nbformat=4.0.1=py27_0
ncl=6.4.0=0
netcdf-fortran=4.4.4=2
netcdf4=1.2.7=np110py27_0
networkx=1.10=py27_0
nltk=3.1=py27_0
node-webkit=0.10.1=0
nose=1.3.7=py27_0
notebook=4.0.6=py27_0
numba=0.22.1=np110py27_0
numexpr=2.6.1=np110py27_1
numpy=1.10.4=py27_0
odo=0.3.4=py27_0
openjpeg=2.1.2=2
openpyxl=2.2.6=py27_0
openssl=1.0.2g=0
owslib=0.10.0=py27_0
pandas=0.19.2=np110py27_1
partd=0.3.2=py27_1
path.py=8.1.2=py27_1
patsy=0.4.0=np110py27_0
pbr=1.3.0=py27_0
pep8=1.6.2=py27_0
pexpect=3.3=py27_0
pickleshare=0.5=py27_0
pillow=3.2.0=py27_1
pip=8.1.1=py27_1
pixman=0.34.0=0
ply=3.8=py27_0
progressbar=2.3=py27_0
proj.4=4.9.1=1
proj4=4.9.3=3
psutil=3.3.0=py27_0
ptyprocess=0.5=py27_0
py=1.4.30=py27_0
pyasn1=0.1.9=py27_0
pyaudio=0.2.7=py27_0
pycosat=0.6.1=py27_0
pycparser=2.14=py27_0
pycrypto=2.6.1=py27_0
pycurl=7.19.5.1=py27_3
pyepsg=0.2.0=py27_0
pyevtk=1.0.0=py27_0
pyflakes=1.0.0=py27_0
pygments=2.0.2=py27_0
pyopenssl=16.2.0=py27_0
pyparsing=2.0.3=py27_0
pyproj=1.9.5.1=py27_0
pyqt=4.11.4=py27_2
pyshp=1.2.3=py27_0
pytables=3.3.0=np110py27_0
pytest=2.8.1=py27_0
python=2.7.12=1
python-dateutil=2.4.2=py27_0
python.app=1.2=py27_4
pytz=2015.7=py27_0
pyyaml=3.11=py27_1
pyzmq=15.2.0=py27_0
qt=4.8.7=4
qtconsole=4.1.1=py27_0
readline=6.2=2
redis=2.6.9=0
redis-py=2.10.3=py27_0
requests=2.13.0=py27_0
rope=0.9.4=py27_1
ruamel_yaml=0.11.14=py27_0
scikit-image=0.11.3=np110py27_0
scikit-learn=0.17.1=np110py27_0
scipy=0.17.0=np110py27_0
setuptools=20.3=py27_0
shapely=1.5.12=np110py27_0
simplegeneric=0.8.1=py27_0
singledispatch=3.4.0.3=py27_0
sip=4.18=py27_0
six=1.10.0=py27_0
snowballstemmer=1.2.0=py27_0
sockjs-tornado=1.0.1=py27_0
sphinx=1.3.1=py27_0
sphinx_rtd_theme=0.1.7=py27_0
spyder=2.3.8=py27_0
spyder-app=2.3.8=py27_0
sqlalchemy=1.0.9=py27_0
sqlite=3.13.0=0
ssl_match_hostname=3.4.0.2=py27_0
statsmodels=0.6.1=np110py27_0
sympy=0.7.6.1=py27_0
terminado=0.5=py27_1
tk=8.5.18=0
toolz=0.7.4=py27_0
tornado=4.3=py27_0
traitlets=4.0.0=py27_0
udunits2=2.2.23=0
ujson=1.33=py27_0
unicodecsv=0.14.1=py27_0
vtk=6.3.0=py27_1
werkzeug=0.11.2=py27_0
wheel=0.29.0=py27_0
xarray=0.9.2=py27_0
xerces-c=3.1.4=0
xlrd=0.9.4=py27_0
xlsxwriter=0.7.7=py27_0
xlwings=0.5.0=py27_0
xlwt=1.0.0=py27_0
xray=0.7.0=py27_0
xz=5.0.5=0
yaml=0.1.6=0
zeromq=4.1.3=0
zlib=1.2.8=0

**Comment by akturner** [comment] 2017-04-17 17:03
OK, using the install commands given by xylar it seems to have made progress. Now the error is:

pn1512828:MPAS-Analysis akt$ ./run_analysis.py config.setup

Plotting sea-ice area and volume time series...

  Reading files:
    timeSeriesStatsMonthly.1959-12.nc through
    timeSeriesStatsMonthly.1962-01.nc
  Load sea-ice data...
   Warning: Preprocessed time series ends before the timeSeries startYear and will not be plotted.
   Caching NH data
   Read in previously computed time series
  Make NH plots...
   Caching SH data
   Read in previously computed time series
  Make SH plots...

Plotting 2-d maps of sea-ice concentration and thickness climatologies...

  Reading files:
    timeSeriesStatsMonthly.1959-12.nc through
    timeSeriesStatsMonthly.1962-01.nc
  Load sea-ice data...
  Compute seasonal climatologies...
  Make ice concentration plots...
   Computing and caching climatologies covering 1-year spans...
     1960
syncing
     1961
syncing
   Computing aggregated climatology 1960-1961...
syncing
syncing
Input #00: /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc
PDQ(in)  : /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc
PDQ(out) : /var/folders/s4/jxqyln_57sgfl3lj2f1329740000gp/T/ncremap_tmp_pdq.nc.pid20078
dyld: Library not loaded: @rpath/libgslcblas.0.dylib
  Referenced from: /Users/akt/anaconda/bin/ncpdq
  Reason: Incompatible library version: ncpdq requires version 1.0.0 or later, but libgslcblas.0.dylib provides version 0.0.0
/Users/akt/anaconda/bin/ncremap: line 1239: 20107 Trace/BPT trap: 5       ncpdq -O --no_tmp_fl --gaa remap_script=ncremap --gaa remap_command="'/Users/akt/anaconda/bin/ncremap -R --rgr lat_nm=lat --rgr lon_nm=lon -i /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc -m /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//mapping/map_QU60_polar_to_0.5x0.5degree_bilinear.nc -o /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/regridded/iceConcentration_QU60_polar_to_0.5x0.5degree_JJA_years1960-1961.nc -P mpas -C'" --gaa remap_hostname=pn1512828.lanl.gov --gaa remap_version= --hdr_pad=10000 -a Time,nVertLevels,maxEdges,MaxEdges2,nCategories,ONE,nEdges,nCells /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc /var/folders/s4/jxqyln_57sgfl3lj2f1329740000gp/T/ncremap_tmp_pdq.nc.pid20078
ncremap: ERROR Failed to generate pdq-file. Debug this:
ncpdq -O --no_tmp_fl --gaa remap_script=ncremap --gaa remap_command="'/Users/akt/anaconda/bin/ncremap -R --rgr lat_nm=lat --rgr lon_nm=lon -i /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc -m /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//mapping/map_QU60_polar_to_0.5x0.5degree_bilinear.nc -o /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/regridded/iceConcentration_QU60_polar_to_0.5x0.5degree_JJA_years1960-1961.nc -P mpas -C'" --gaa remap_hostname=pn1512828.lanl.gov --gaa remap_version= --hdr_pad=10000  -a Time,nVertLevels,maxEdges,MaxEdges2,nCategories,ONE,nEdges,nCells /Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc /var/folders/s4/jxqyln_57sgfl3lj2f1329740000gp/T/ncremap_tmp_pdq.nc.pid20078
Traceback (most recent call last):
  File "./run_analysis.py", line 230, in <module>
    analysis(config)
  File "./run_analysis.py", line 182, in analysis
    seaice_modelvsobs(config)
  File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/sea_ice/modelvsobs.py", line 105, in seaice_modelvsobs
    _compute_and_plot_concentration(config, ds, mpasMappingFileName, calendar)
  File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/sea_ice/modelvsobs.py", line 214, in _compute_and_plot_concentration
    overwrite=overwriteMpasClimatology)
  File "/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/MPAS-Analysis/mpas_analysis/shared/interpolation/interpolate.py", line 226, in remap
    subprocess.check_call(args)  # }}}
  File "/Users/akt/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ncremap', '-R', '--rgr lat_nm=lat --rgr lon_nm=lon', '-i', '/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/iceConcentration_QU60_polar_JJA_years1960-1961.nc', '-m', '/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//mapping/map_QU60_polar_to_0.5x0.5degree_bilinear.nc', '-o', '/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//clim/mpas/regridded/iceConcentration_QU60_polar_to_0.5x0.5degree_JJA_years1960-1961.nc', '-P', 'mpas', '-C']' returned non-zero exit status 1

I know I need to generate mapping files for this mesh, which may be the problem here? Are there instructions of how to do that, where to put them?

**Comment by xylar** [comment] 2017-04-18 08:54
@akturner, you shouldn't need to create mapping files in advance.  They should be created automatically if you don't point to existing mapping files.  Indeed, it looks like it at least *thinks* it created the file:
```
/Users/akt/Work/MPAS-CICE/MPAS-Analysis/feature_branches/standalone/development/rundir//mapping/map_QU60_polar_to_0.5x0.5degree_bilinear.nc
```
Could you verify that files exists and looks like a valid NetCDF file (e.g. with `ncdump -h`)?

It doesn't look like the mapping file is the problem, though.  It looks like you have two conflicting versions of `libgslcblas.0.dylib` installed.  I would suggest uninstalling whatever previous version of NCO you have installed on your Mac outside of conda (as well as its dependencies including gslcblas) and just using the version installed by conda.

**Comment by xylar** [comment] 2017-04-18 08:55
Also, I would argue that this is not a bug in MPAS-Analysis but rather a complication in setting up NCO via conda and also via another installer.  I'm going to remove the bug label that @pwolfram added.

**Comment by akturner** [comment] 2017-04-18 15:47
Yeah, the python install I did above has broken nco on my laptop. I have no recollection on how this was originally installed, so will have to figure that out.

**Comment by akturner** [comment] 2017-04-18 15:48
And uninstalling nco from conda still leaves my nco broken

**Comment by xylar** [comment] 2017-04-18 16:37
@akturner, we require one of the latest versions of nco to support ncremap. We also need esmf, a dependency of at least the conda version of nco. I would advise getting help from someone who has recently successfully installed both nco and esmf on the mac. Unfortunately, I don't have a mac to play with.

**Comment by akturner** [comment] 2017-04-21 21:08
Could this have also broke my install on mpi? I can't build MPAS anymore with the following error, and all I've really tried to do in the interim is build this?

mpif90 -D_MPI -DUNDERSCORE -DCORE_CICE -DMPAS_NAMELIST_SUFFIX=cice -DMPAS_EXE_NAME=cice_model -DMPAS_NATIVE_TIMERS -DMPAS_GIT_VERSION=v5.0-440-g1b5db29 -O3 -m64 -ffree-line-length-none -fconvert=big-endian -ffree-form -fdefault-real-8 -fdefault-double-8 -c mpas_abort.F -I/Users/akt/Work/libraries/pio/ParallelIO-pio1_7_2/pio -I/Users/akt/Work/libraries/pnetcdf/pnetcdf-1.7.0//include -I/Users/akt/Work/libraries/netcdf/netcdf/include -I/Users/akt/Work/libraries/pio/ParallelIO-pio1_7_2/pio -I/Users/akt/Work/libraries/pnetcdf/pnetcdf-1.7.0//include -I/Users/akt/Work/libraries/netcdf/netcdf/include -I/Users/akt/Work/MPAS-CICE/satisfy_pull_requests/log_testing/base/MPAS/src/core_cice/column -I/Users/akt/Work/MPAS-CICE/satisfy_pull_requests/log_testing/base/MPAS/src/core_cice/shared -I/Users/akt/Work/MPAS-CICE/satisfy_pull_requests/log_testing/base/MPAS/src/core_cice/analysis_members -I/Users/akt/Work/MPAS-CICE/satisfy_pull_requests/log_testing/base/MPAS/src/core_cice/model_forward -I../external/esmf_time_f90
mpas_abort.F:35.10:

      use mpi
          1
Fatal Error: Cannot read module file 'mpi.mod' opened at (1), because it was created by a different version of GNU Fortran

**Comment by akturner** [comment] 2017-04-21 21:14
Yep, it appears mpif90 now points to the anaconda version

**Comment by vanroekel** [comment] 2017-04-21 21:18
I do remember this happening.  If you add the conda path to your PATH variable first (before wherever mpi is installed), it should work.  i believe the conda installer prepends the path after everything you put in .bashrc (or whatever shell you use).  Another possible solution may be to just move the offending executable from ../conda/bin so it finds the correct one.

**Comment by xylar** [comment] 2017-04-21 21:20
Yeah, it's best not to install mpi (or anything that depends on it through conda).  I would suggest deleting your conda installation and starting over.  Whatever tried to install mpi, don't install that.  If you absolutely need it, set up a separate conda environment for it (with conda create) that you only use when you need that tool.

conda can be great until it starts installing bad versions of binaries like compilers and mpi.  Then it's really the pits!

**Comment by akturner** [comment] 2017-04-21 21:20
@xylar: This would only have been the MPAS-Analysis system installation attempt

**Comment by xylar** [comment] 2017-04-21 21:21
Nothing there should depends on mpi.  I've been careful about that.

**Comment by xylar** [comment] 2017-04-21 21:27
I'm doing a new install and, indeed, something is trying to install mpich.  I'll try to find out what.

**Comment by akturner** [comment] 2017-04-21 21:36
It seems to make a symbolic link in /Users/akt/anaconda/bin from mpif90 to mpifort. In this case it links to my macports install of openmpi, i.e. mpifort points to my macports install. Dont know why it did that. Removing anaconda from my PATH recovers use of nco and mpi.

**Comment by xylar** [comment] 2017-04-21 21:36
Shoot!  This seems to be the latest `nco`.  We should find out from Charlie Zender if this is something they did on purpose because it seems like exactly the kind of thing that really messes up a conda install.  You can't be messing up people's existing MPI settings by overriding them in the anaconda environment.

**Comment by akturner** [comment] 2017-04-21 21:37
Indeed! So Rude! :-)

**Comment by xylar** [comment] 2017-04-21 21:40
If you do `conda remove mpich`, that should remove mpi and all packages that depend on it.  Then, you should be able to install `nco=4.6.0` without installing mpich.  Every minor version after that depends on mpich.

**Comment by xylar** [comment] 2017-04-21 21:42
Okay, wait.  The plot thickens.  It doesn't seem like nco is the problem, it's esmf, which is a dependency that we need.

**Comment by akturner** [comment] 2017-04-21 21:44
Is there a way to do the conda installs in a sand box? Like a conda environment - something like this: http://www.ncl.ucar.edu/Download/conda.shtml

**Comment by xylar** [comment] 2017-04-21 21:45
Yeah, sure.  Just install miniconda to a new location, prepend that path to your $PATH variable, and play around.  That's what I'm doing right now.

**Comment by xylar** [comment] 2017-04-21 21:46
Yep, or you can also use conda  create off of an existing conda install.  That works, too.  It's a little more complicated to clean up later.

**Comment by xylar** [comment] 2017-04-21 21:52
Okay, well I didn't notice this until now, but mpich appears to be part of the list of packages that we're using on edison, too.  So I guess if we want to use esmf through conda we're going to get mpich along for the ride.  That's a big pain...

I guess I would go with @vanroekel's suggestions if either of them are practical: preferably putting the path to the mpi libraries you want before the path to your anaconda installation.  If that isn't practical, just manually move the mpi* executables somewhere else.

I would recommend making an anaconda environment specifically for MPAS-Analysis with conda create.  Then, you can (if you use bash shell) run "source activate mpas_analysis" to switch to that environment and "source deactivate" to go back to your normal anaconda environment that's maybe uncontaminated with mpi and such nonsense.

**Comment by xylar** [comment] 2017-08-12 17:59
@akturner, having not heard anything further on this issue, I'm going to close it.  If you still don't have MPAS-Analysis working on your (new) laptop, please re-open and I'll try to work you through what I did when I recently had to set up MPAS, its dependencies and MPAS-Analysis on my laptop.

**Closed by xylar** 2017-08-12 17:59 UTC
