### ISSUE TITLE
MPAS-Analysis does not run on OLCF

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#134] opened 2017-03-13 04:29 UTC
Following the switch to ncremap, MPAS-Analysis does not work on OLCF.  @pwolfram's conda install does not have esmf installed preventing any regrinding from working.

Also, the MPAS-Analysis config file for OLCF is broken.  It is missing ```mappingSubdirectory```.  I will fix and make a small PR.

**Comment by milenaveneziani** [comment] 2017-03-13 05:51
Thanks for reporting this, @vanroekel. Indeed we need to update the conda packages on OLCF, NERSC and aims. I can do aims. @pwolfram, @xylar: could you please take care of the other two? Our LANL package is set. thanks.

**Comment by xylar** [comment] 2017-03-13 07:09
@milenaveneziani and @pwolfram, I am taking care of edison right now and will check on cori shortly after.

Here are the commands:
```
conda config --add channels conda-forge
conda install numpy scipy matplotlib netCDF4 xarray dask bottleneck basemap nco fasteners
```
Note the `fasteners` package is not needed now but will be required for parallel tasks.

**Comment by xylar** [comment] 2017-03-13 08:16
One more note, after the upgrade of `xarray`, it is possible that the current version of `MPAS-Analysis` in `ACMEPreAndPostProcessingScripts` will no longer work.  @milenaveneziani, can you test this?  If not, we will need to put together a patch quickly!

**Comment by xylar** [comment] 2017-03-13 13:44
@milenaveneziani, I don't have an OLCF account, so either @pwolfram or @vanroekel will need to do this (depending on who set up the original anaconda installation and who has permission to update it).

**Comment by vanroekel** [comment] 2017-03-13 13:47
@xylar, @milenaveneziani, I tried, but don't have write permission, so @pwolfram will have to update.

**Comment by milenaveneziani** [comment] 2017-03-13 15:40
@xylar: that is a good point. I just tested `ACMEPreAndPostProcessing` now and indeed I got this error:
```
Traceback (most recent call last):
  File "python/MPAS-Analysis/run_analysis.py", line 182, in <module>
    analysis(config)
  File "python/MPAS-Analysis/run_analysis.py", line 99, in analysis
    variableMap=oceanVariableMap)
  File "/global/u2/m/milena/ACME-PreAndPostProcessing/coupled_diags/python/MPAS-Analysis/mpas_analysis/ocean/ohc_timeseries.py", line 132, in ohc_timeseries
    preprocess=lambda x: preprocess_mpas(x,
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/backends/api.py", line 509, in open_mfdataset
    datasets = [preprocess(ds) for ds in datasets]
  File "/global/u2/m/milena/ACME-PreAndPostProcessing/coupled_diags/python/MPAS-Analysis/mpas_analysis/ocean/ohc_timeseries.py", line 136, in <lambda>
    varmap=variableMap))
  File "/global/u2/m/milena/ACME-PreAndPostProcessing/coupled_diags/python/MPAS-Analysis/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 315, in preprocess_mpas
    datetimes = get_datetimes(ds, timestr, yearoffset)
  File "/global/u2/m/milena/ACME-PreAndPostProcessing/coupled_diags/python/MPAS-Analysis/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 164, in get_datetimes
    ends = get_datetimes(ds, timestr[1], yearoffset)
  File "/global/u2/m/milena/ACME-PreAndPostProcessing/coupled_diags/python/MPAS-Analysis/mpas_analysis/shared/mpas_xarray/mpas_xarray.py", line 177, in get_datetimes
    for x in time]
ValueError: invalid literal for int() with base 10: ''
```
which resembles the restart problem we were seeing before, but I made sure to exclude year 1 from the time series because I knew that the very first file was corrupted (0001-01-01). So, do you think this is due to the newer xarray?

Besides this, people will still have problems running the current ACME analysis because we don't have remapping files for the EC60to30v3 grid..

**Comment by vanroekel** [comment] 2017-03-13 15:58
@xylar and @milenaveneziani I was able to get OLCF working again with my own conda install.  I've also fixed the titan config file (see #135).  @milenaveneziani, do you expect a need for remapping files for the EC6030v3?  I've run the mpas-analysis on v3 with no apparent issues.  Is this because develop hasn't been pulled to the ACME side?

Example output for 18to6v3 below (this output is year 4 only, not 4-20)

![iceconcbootstrapnh_gmpas-iaf_orrs18to6v3_jfm_years0004-0020](https://cloud.githubusercontent.com/assets/13662545/23862788/8e0d2116-07d3-11e7-9a0b-90b688afa70b.png)
![iceconcbootstrapsh_gmpas-iaf_orrs18to6v3_djf_years0004-0020](https://cloud.githubusercontent.com/assets/13662545/23862790/8e20fc0e-07d3-11e7-8c3e-7b0e8ef43c60.png)
![ssthadoi_gmpas-iaf_orrs18to6v3_ann_years0004-0020](https://cloud.githubusercontent.com/assets/13662545/23862789/8e1c50b4-07d3-11e7-9fcd-eda52a5e3633.png)

**Comment by milenaveneziani** [comment] 2017-03-13 16:05
@vanroekel: yes, it's because develop hasn't been pulled in ACME analysis yet (it's not that immediate, especially now that we have advanced MPAS-Analysis quite a bit with respect to master).
But I am thinking/seeing two things:
1) if I run MPAS-Analysis on beta1, I can create a mapping file for v3, so that will solve this problem;
2) I just tried to do just that, but I am getting the same error as the one I reported above, so this has to have nothing to do with the newer xarray. I am not sure what could be wrong though, since all the beta1 mpas files look OK if we exclude the very first year. I will look into it now..

**Comment by xylar** [comment] 2017-03-13 16:14
@milenaveneziani, could you post a separate issue with the problems you're having with `ACMEPreAndPostProcessingScripts` on Edison?  I think the issue should be here, rather than in that repo.  Then, we can discuss that issue in that issue.

**Comment by milenaveneziani** [comment] 2017-03-13 16:15
I know what is the cause of 2.: the OHC relies on the first year of data. So I will have to skip that for the time being (or have it compute the anomaly wrt the second year of beta1, just for today..).

**Comment by xylar** [comment] 2017-03-13 16:30
@milenaveneziani, glad you figured out the error.  I'm almost completely sure it's caused by the same issue we saw before (#126) where there is more than one xtime in at least one file.

**Comment by milenaveneziani** [comment] 2017-03-13 16:40
@xylar: indeed. I turned off the OHC trend calculation in ACMEPreAndPostProcessing, and things worked: so at least we are sure that the new conda environment does not break it. Phew.
Just for today's coupled telecon, I computed OHC starting from year 2, and things seemed to have worked.
We'll still have the problem of the sea-ice climos in ACME-Analysis, before I pull in MPAS-Analysis into ACMEPreAndPostProcessing. I have to decide what to prioritize: that or the MOC postprocessing. It's hard to decide, since MOC is almost ready..

**Comment by pwolfram** [comment] 2017-03-13 16:57
@xylar, I've updated the OLCF conda installation as requested.

**Comment by xylar** [comment] 2017-03-13 17:47
@pwolfram, great, thanks!

**Comment by milenaveneziani** [comment] 2017-03-13 17:50
And I have updated on aims, so I think we can close this issue?

**Comment by vanroekel** [comment] 2017-03-13 17:57
I think so., one request.  The Readme for mpas-analysis is out of date.  Can we add a reference that  baseman is needed and include @xylar 's instructions for installing esmf? i.e.,
```
conda config --add channels conda-forge
conda install numpy scipy matplotlib netCDF4 xarray dask bottleneck basemap nco fasteners
conda update --all
```
This would be useful for those (like myself) who prefer to setup their own environment.

**Comment by xylar** [comment] 2017-03-13 18:10
I have just such a change to the readme as part of one of my 2 pending PRs (I can't remember which, but probably #129).  I think the `conda update --all` is not necessary to include.  That's like telling people to keep their software up to date.  Your digital hygiene is, at some level, your own business...

**Comment by vanroekel** [comment] 2017-03-13 18:14
Fair enough about update --all, got carried away on the copy paste!  I just want to make sure ESMF was included.  The error that results when this is not installed is not clear that it is a missing package.  It looks like your PR will definitely address this issue.

**Comment by xylar** [comment] 2017-03-13 18:28
@vanroekel, that's kind of a tough one.  Could you submit an issue about missing ESMF specifically?  Future anaconda installations shouldn't run into that issue but current ones with older versions of NCO won't include ESMF.  What we should be doing is making sure ESMF_RegridWeightGen exists in the path and warn the user if it's not present.  That's not super easy but would be helpful to a user.

**Comment by xylar** [comment] 2017-03-14 08:39
@vanroekel, this shouldn't be too hard to add, using the utility `distutils.spawn.find_executable` (or something similar):
http://epydoc.sourceforge.net/stdlib/distutils.spawn-module.html#find_executable

It would be good to check for both `ESMF_RegridWeightGen` and `ncremap` at the beginning of their respective calls in interpolate, and bail if it's not there.  I'll add that now.

**Comment by xylar** [comment] 2017-03-14 12:53
@milenaveneziani and @vanroekel, so I ran the latest `ACME/PreAndPostProcessingScripts` on edison and I am, indeed, seeing the same errors in the MLD analysis that we saw in `MPAS-Analysis` when we upgraded to `xarray/0.9.1`:
```
  np.nansum(daysarray[monthsvalue-1, :, :], axis=0))
Traceback (most recent call last):
  File "python/MPAS-Analysis/run_analysis.py", line 182, in <module>
    analysis(config)
  File "python/MPAS-Analysis/run_analysis.py", line 138, in analysis
    variableMap=oceanVariableMap)
  File "/global/u2/x/xylar/acme_work/analysis/xylar/update_MPAS_Analysis_v0.2/coupled_diags/python/MPAS-Analysis/mpas_analysis/ocean/ocean_modelvsobs.py", line 229, in ocn_modelvsobs
    dsData.sel(month=monthsvalue)[obsFieldName].values, axis=0) /
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/core/dataset.py", line 1184, in sel
    result = self.isel(drop=drop, **pos_indexers)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/core/dataset.py", line 1119, in isel
    new_var = var.isel(**var_indexers)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/core/variable.py", line 547, in isel
    return self[tuple(key)]
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/core/variable.py", line 377, in __getitem__
    values = self._indexable_data[key]
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/xarray/core/indexing.py", line 486, in __getitem__
    value = value[(slice(None),) * axis + (subkey,)]
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/dask/array/core.py", line 1228, in __getitem__
    dsk, chunks = slice_array(out, self.name, self.chunks, index)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/dask/array/slicing.py", line 139, in slice_array
    dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/dask/array/slicing.py", line 161, in slice_with_newaxes
    dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/dask/array/slicing.py", line 202, in slice_wrap_lists
    check_index(i, sum(bd))
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/lib/python2.7/site-packages/dask/array/slicing.py", line 713, in check_index
    raise IndexError("Index out of bounds %s" % dimension)
IndexError: Index out of bounds 12
```
This means that diagnostics are currently broken on Edison (and presumably elsewhere where xarray has been updated) and should be fixed sooner rather than later.

**Comment by xylar** [comment] 2017-03-14 12:55
I think we shouldn't do any further merges, but should instead focus on merging what we currently have to `master` and updating ACME to work with it.

**Comment by milenaveneziani** [comment] 2017-03-14 15:06
Interesting that I didn't get this error yesterday.
Can we downgrade xarray in the main conda packages, so that we can run MPAS-Analysis with our own environments?
I am wary of doing a merge to ACME master now. I am focused on the MOC and would really like to get it done this week. Updating the MPAS submodule would be a major distraction right now, and it may take a while anyway, so we may have to think of a temporary downgrade of xarray anyway.

**Comment by milenaveneziani** [comment] 2017-03-14 15:07
Also, quick question: do we *need* the upgraded xarray, or is it that we just need nco/esmf?

**Comment by xylar** [comment] 2017-03-14 15:21
I don't know how to downgrade xarray.  Once there's a new version, older versions are generally not kept in the conda channels.  Maybe @pwolfram has some advice here.  I don't even really know how to find out what previous versions are available.

Yes, we needed to update nco to get esmf.  I wanted to update the repo generally in that process.

I have a branch where I tested updating MPAS-Analysis within PreAndPostProcessingScripts:
https://github.com/ACME-Climate/PreAndPostProcessingScripts/tree/xylar/update_MPAS_Analysis_v0.2
I had to do some updates to the script for converting environment variables to config options (of course) and make one small change to the 4 run_<machine>.csh scripts but otherwise everything worked like a charm!

**Comment by xylar** [comment] 2017-03-14 15:24
@milenaveneziani, I figured out the downgrading of xarray.  I'll try various versions.

**Comment by xylar** [comment] 2017-03-14 15:24
We may have to do the same on aims and at oak ridge.

**Comment by milenaveneziani** [comment] 2017-03-14 15:31
I can certainly take care of aims.
thanks for looking into this.

That's great that you already have a branch for updating ACME analysis.

**Comment by xylar** [comment] 2017-03-14 15:31
Okay, I downgraded to xarray 0.8.2:
```
conda install xarray=0.8.2
```
and it seems to work again.  I'll do the same on cori.  @milenaveneziani, can you do this on aims and @pwolfram on OLCF?

**Comment by vanroekel** [comment] 2017-03-14 15:32
@xylar and @milenaveneziani I have run two separate cases on Anvil and Titan through MPAS analysis (develop) and have no issues with MLD analysis.  My conda environment on both machines has xarray 0.9.1  Is this error an edison specific issue?

**Comment by xylar** [comment] 2017-03-14 15:34
@vanroekel, the issue is with the version of `MPAS-Analysis` used by `PreAndPostProcessingScripts`, not with `develop`.  I assume you're running from `develop`?

**Comment by vanroekel** [comment] 2017-03-14 15:35
I see.  yes I am running with develop.

**Comment by xylar** [comment] 2017-03-14 15:36
@milenaveneziani, I think my branch will still be very useful for next week or whenever we're actually ready to update `PreAndPostProcessingScripts`.

**Comment by milenaveneziani** [comment] 2017-03-14 15:51
downgraded xarray on aims.
Once we are done, let's leave this issue open, so we'll be sure to remember to re-upgrade..

**Comment by vanroekel** [comment] 2017-03-14 17:24
@xylar and @milenaveneziani, given #135 and #138, I think this issue is fully addressed.  Any objections to closing?

**Comment by milenaveneziani** [comment] 2017-03-14 17:29
@xylar: I was thinking to keep it open so that we can remember to re-upgrade xarray after develop has been pulled in into ACME. But if you have a better memory than mine, we can close it :)

**Comment by xylar** [comment] 2017-03-14 17:45
@milenaveneziani, I think we can close it.  I won't forget.  In general, we should try to keep our conda repos updated because then they will tend to stay more similar to one another.

**Closed** 2017-03-14 18:15 UTC
