### ISSUE TITLE
Task fails silently if dependent task previously failed 

### ISSUE THREAD

**Issue by pwolfram** [MPAS-Dev/MPAS-Analysis#440] opened 2018-07-19 18:55 UTC
Task with failed dependency should report an error that it will not be run due to dependent task failure.

**Comment by xylar** [comment] 2018-07-19 21:49
@pwolfram, there's a bit of code that *should* be printing a warning when a "prerequisite" task fails during setup:
https://github.com/MPAS-Dev/MPAS-Analysis/blob/develop/run_mpas_analysis#L253

I could use some help figuring out why it's not getting triggered in your particular case.  Could you post your config file here and let me know what machine it's for?  That'd help me debug.

**Comment by xylar** [comment] 2018-07-19 22:06
@pwolfram, I think I've got a run to try out (@bradyrx's config file in the #329)

**Comment by xylar** [comment] 2018-07-19 22:22
@pwolfram, I ran with that setup and I see an error:
```
Traceback (most recent call last):
  File "./run_mpas_analysis", line 286, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/turquoise/usr/projects/climate/xylar/mpas_work/analysis/add_bgc_skill_scores/mpas_analysis/shared/climatology/remap_mpas_climatology_subtask.py", line 209, in setup_and_check
    self.mpasClimatologyTask.add_variables(self.variableList, self.seasons)
  File "/turquoise/usr/projects/climate/xylar/mpas_work/analysis/add_bgc_skill_scores/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 155, in add_variables
    'output:\n{}'.format(variable, self.allVariables))
ValueError: timeMonthly_avg_ecosys_diag_pCO2surface is not available in timeSeriesStatsMonthly output:
[u'timeMonthly_counter', u'xtime_startMonthly', u'xtime_endMonthly', 
...
u'timeMonthly_avg_iceFluxDust', u'timeMonthly_avg_iceFluxDOC', u'timeMonthly_avg_iceFluxDON']
ERROR: analysis task climatologyMapBGC_pCO2surface: remapMpasClimatology failed during check and will not be run
ERROR: a subtask of analysis task climatologyMapBGC_pCO2surface failed during check,
       so this task will not be run
ERROR: prerequisite task climatologyMapBGC_pCO2surface of analysis task climatologySkillScoreBGC failed during check,
```
Note the mention of `climatologySkillScoreBGC`, as expected.

So I'm not able to reproduce this problem.

**Comment by xylar** [comment] 2018-07-20 18:34
@pwolfram, we figured out that the issue is not that the task is failing silently but rather that you were disabling a task but then it was getting re-enabled because it is a prerequisite of another task.  The solution will be a refactoring of the BGC tasks in the near future.  I think we can close this issue.

**Closed by xylar** 2018-07-20 18:34 UTC
Labels: bug

**Comment by pwolfram** [comment] 2018-07-20 19:40
Agreed, thanks for the help @xylar!
