### ISSUE TITLE
mpas-analysis does not support cdf-5 format files with e3sm-unified 1.2.2 and 1.2.3

### ISSUE THREAD

**Issue by vanroekel** [MPAS-Dev/MPAS-Analysis#459] opened 2018-10-19 04:13 UTC
I tried running mpas-analysis (up to date version of develop) on the high res output on NERSC and get a log file full of errors like 
```
:--:--Traceback (most recent call last):
  File "./run_mpas_analysis", line 275, in add_task_and_subtasks
    analysisTask.setup_and_check()
  File "/global/u2/l/lvroekel/MPAS-Analysis/mpas_analysis/shared/climatology/mpas_climatology_task.py", line 216, in setup_and_check
    with xarray.open_dataset(self.inputFiles[0]) as ds:
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.2_py2.7_nox/lib/python2.7/site-packages/xarray/backends/api.py", line 320, in open_dataset
    **backend_kwargs)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.2_py2.7_nox/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 332, in open
    ds = opener()
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.2_py2.7_nox/lib/python2.7/site-packages/xarray/backends/netCDF4_.py", line 231, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2126, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1368, in netCDF4._netCDF4._get_format
ValueError: format not supported by python interface
ERROR: analysis task mpasClimatologyOcean failed during check and will not be run
```

If I return to e3sm-unified 1.2.0 the analysis runs okay.  I assume this is related either xarray, nco, or netcdf4 versioning and how it interacts with cdf5 files.

The config file is at ```/global/homes/l/lvroekel/MPAS-Analysis/config.highRes```

**Comment by vanroekel** [comment] 2018-10-19 04:59
UPDATE: this problem also occurs on ALCF (theta).

**Comment by xylar** [comment] 2018-10-19 13:50
@vanroekel, thanks for pointing out this issue.  I can't read `/global/homes/l/lvroekel/MPAS-Analysis/config.highRes`.  The error is a starting point butt I'm looking into it further to see *why* cdf5 isn't supported and what we can do about it.  It would be helpful to know what the python NetCDF4 library *thinks* the format is.  (Which should have been in the error message, in my view, but that's a side issue.)

**Comment by vanroekel** [comment] 2018-10-19 14:31
Sorry about that, try again now.

**Comment by xylar** [comment] 2018-10-19 14:43
Yep, got it.  And I'm able to reproduce the problem.

**Comment by xylar** [comment] 2018-10-20 12:57
Should be addressed by https://github.com/conda-forge/netcdf4-feedstock/pull/68 but I'll need to make sure e3sm-unified pulls in this version of `netCDF4` once it's uploaded to the conda-forge channel.  There may be conflicts with other packages that prevent this new build from being selected.

**Comment by xylar** [comment] 2018-10-22 21:59
@vanroekel, I have just (seconds ago) created a new e3sm-unified 1.2.3 environment on edison.  Could you activate it by sourcing the following?
```
/global/project/projectdirs/acme/software/anaconda_envs/load_latest_e3sm_unified.sh
```
Could you see if the CDF-5 issue is fixed?  Fingers firmly crossed.

**Comment by xylar** [comment] 2018-10-22 22:00
If the issue is fixed on Edison, I'll install the same version on all the other machines tomorrow and update the instructions for loading e3sm-unified.

**Comment by vanroekel** [comment] 2018-10-23 03:09
@xylar could you change permissions on the script to source?

**Comment by xylar** [comment] 2018-10-23 06:50
Sorry about that.  Permissions should now be fixed.

**Comment by xylar** [comment] 2018-10-23 07:20
I do think it's going to work, but would like you to try the analysis to be sure.  It at least recognizes CDF-5 support:
```
> source load_latest_e3sm_unified.sh 
> python -c "import netCDF4; print(netCDF4.__has_cdf5_format__)"
1
```

**Comment by vanroekel** [comment] 2018-10-23 13:29
Yep, it works!  Thanks for the fix @xylar

**Closed** 2018-10-23 13:33 UTC
