### ISSUE TITLE
Preparing for regression testing

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/MPAS-Analysis#195] opened 2017-04-19 14:19 UTC
We should set up regression tests on each machine that can be run (and checked) with a single script call.  In particular, we need:

- [ ] A way of defining a regression test, presumably via 1 or more config files, some of which are combined for a single analysis run and some of which are run in sequence.  (An example of the latter would be checking that caching works correctly when the start and end year of a time series and/or climatology are changed).
- [ ] An easy way to create a set of baseline results on each machine and a place to store these results.  We probably want a plan for how to update the baseline as new tasks are added or existing tasks change in non-bit-for-bit ways.
- [ ] A way to sets `[output]` `baseDirectory` to an appropriate test directory (probably just a temp directory) as part of launching each regression test.
- [ ] A way to check results (cache files, plots, eventually HTML output) of a regression test against the baseline, presumably with some tolerance for differences (e.g. in metadata, perhaps in data arrays as well).
- [ ] The definition of the regression tests themselves on each machine

I think this will be a considerable effort, and one that I will contribute to as I can.  But I want to make sure the appropriate person-hours are being devoted to this on our side to make sure the efforts by the ACME Workflow Team are met with fruitful collaboration on our side.

**Comment by xylar** [comment] 2017-04-19 14:21
@pwolfram, what is your level of interest and ability to commit time to these needs?  You've been pushing hardest to have regression testing available, which is fantastic.  Can you set up some prototype tests on Edison and perhaps some of the other ACME-supported machines so the Workflow Team has something to test their system with?  Let me know how I can help.

**Comment by pwolfram** [comment] 2017-04-19 15:13
Thank you @xylar for doing this!  @vanroekel came to me this morning on a tangential issue and it is clear we need a way to ensure we get certain behavior on each machine.  Having a way to do machine-specific testing will be key and I think will help alleviate some frustration and unexpected problems we are having with the analysis.  I would make that our top priority in this work.  

The simplest approach is that we should be able to just essentially run

`python run_analysis.py config/specificmachine/*` 

over each config file on each specific machine.  

I agree we need baselines too, but the first step is to just run and make sure it completes, maybe checking for some simple things like that all produced files don't have nans in bad places.  

We can probably just make a temp directory for 
>  A way to sets [output] baseDirectory to an appropriate test directory (probably just a temp directory) as part of launching each regression test.

For 
>  The definition of the regression tests themselves on each machine

What were you thinking?  If we could make the regression test be configurable off a config file that would be cool, but I'm not sure how practical that is relative to just running our existing configuration files.

To be fair, if we just run each config file on each specific machine for
> I think this will be a considerable effort, and one that I will contribute to as I can. But I want to make sure the appropriate person-hours are being devoted to this on our side to make sure the efforts by the ACME Workflow Team are met with fruitful collaboration on our side.

we will have meet the primary need of regression testing in the short term, e.g., to ensure that the analysis doesn't break catestrophically on each platform.  But in the long term we need to go further to make sure that results are reasonable too, which will require greater testing.  If we do it right, we should be able to write tests as bugs come up to automatically test to make sure that a given PR solves the particular bug, similar to what we already do with py.test.


The most pressing question I have for you is "If we just run each config file on each relevant platform will that be enough?"  I think that will catch the bulk of our errors that we have been experiencing, but you and @milenaveneziani should comment on whether you think this is sufficient.  I think it is for the short term target but it clearly is only the first step.  This is the minimal case I had in mind to implement following the ACME Workflow Team's integration of py.test, e.g., run each config file corresponding to each machine, just to make sure an error doesn't result.

As bugs come up we need to write tests to expose the bug to ensure that the bug cannot crop up in the future, e.g., so that if libraries change and the bug reemerges we know this immediately as already demonstrated via our existing use of py.test and the xarray increment to 0.9.

**Comment by pwolfram** [comment] 2017-04-19 15:17
@xylar, to answer

> @pwolfram, what is your level of interest and ability to commit time to these needs?

explicitly, I was just planning on running each machine specific config to test for a crash on each machine as justified in my previous comment.  

Personally-- I have two paper revisions, two proposals, plus the LIGHT integration into ACME over the next month and other assorted project tasks so time is extremely tight but I should be able to make time for this level of effort that should catch 80% of our issues.  Going further as outlined here, however, isn't too realistic for my time commitments in the short term but is obviously needed at longer times scales, corresponding to the level of priority we have placed on this work as a team.  My hope is to contribute more substantially to this after these more immediate time pressures are alleviated.

Also, I would expect we may have some iteration with the workflow team, so starting sooner than later will be beneficial for everyone as long as people aren't artificially pressured as you thankfully pointed out.  Thanks for the help here and for engaging!

**Comment by pwolfram** [comment] 2017-04-19 15:22
@xylar, I should note that since we are just going to be running `py.test` on each machine for

> Can you set up some prototype tests on Edison and perhaps some of the other ACME-supported machines so the Workflow Team has something to test their system with?

we can use the existing py.tests in the short term because we know they should work on each machine out of the box to keep things simple and easy for the workflow team.  Once we have their script to kick off jobs we can make sure our work in py.test still works as we add machine specific tests.  I can't foresee a clear reason why this would create problems.  Do you see something I'm missing here?

**Comment by xylar** [comment] 2017-04-19 18:36
@pwolfram, all of that sounds good.  We will first just used `pytest` on each machine as our regression test. Then, we will prsumably have to write a small driver script that reads each machine-specific config file and sets the output baseDirectory to a temp folder, runs that analysis, logs its success or failure somehow, deletes the folder, and moves on to the next test.  Even finding time to write such a basic driver script will be tricky for me in the next few weeks, to be honest.  This is where I'm concerned about pushing the Workflow Team too hard when we ourselves don't have too much time to put toward this.

**Comment by pwolfram** [comment] 2017-04-19 20:02
@xylar, regarding pushing the Workflow Team too hard-- they have set the schedule.  We are committed to contribute to this process but aren't committed to deliver a fully functioning regression test suite by the time they have the system implemented.  However, we likely need that system to start to do this work ourselves, at least to some degree.  Is there something I'm missing here?  Is there some type of expectation that we deliver more than our pre-existing `pytest` test suite?  I don't think there is because on their end providing a testing platform is what matters and they will be able to do that-- we will of course be flexible if they need to modify tasks, schedule, etc.  I'm happy to have a meeting with you and Dean to discuss further if you want because I fully agree with you that we don't want to cause them problems- we are grateful for their specialized help!

**Comment by milenaveneziani** [comment] 2017-04-19 20:19
From what I understand, the point of having this issue open is to scope out tasks that are needed, on our side, to prepare for anything that the workflow team will do to help us with regression testing. Is that correct?
If so, my approach would be to 1) decide whether we can do all this, when, etc; and 2) share the list of tasks with the workflow team to see if we missed something, or if there is something that is absolutely needed within the schedule they have in mind.

**Comment by pwolfram** [comment] 2017-04-19 20:38
@milenaveneziani, once we have a way to run pytest on each LCF and aggregate results automatically then all this is up to us.  I don't think it has anything to do with the Workflow team.  We need LCF integration with github to automate regression testing in a clean way, then our tasks should be fairly independent of the Workflow team, who are essentially bridging the gap of travis CI being run on servers on the web (not helpful if we run specific configurations) to pytest being run on specific LCFs with the results reported to github, which prepares the way for us to fully implement regression testing.

In sum, I would argue that our work is largely independent of the Workflow team.  Am I missing something here @xylar and @milenaveneziani?

**Comment by xylar** [comment] 2017-04-19 20:41
@milenaveneziani, yep, that's exactly what I had in mind.  

@pwolfram said on our last conference call that we needed this functionality from them as soon as possible.  I think they're making it a high priority because of that, which is great.  I'm just wanting to make sure we are getting good use of the that effort, especially because they are making it a priority.  I don't feel like running `pytest` as it stands on each machine is really doing that, though I do agree that it's an excellent starting point.  I *do* agree that running each existing test case that we support and making sure it doesn't crash would be a very good start.  So let's make sure we can get to that point soon.

**Closed** 2017-11-07 22:20 UTC
